#!/bin/sh
PYBIN="/usr/bin/env python3"
DIR=$(dirname "$(readlink -f "$0")")
PYTHONVERSION=`$PYBIN --version | sed 's/Python 3\.\([0-9]*\)\.[0-9]*/\1/'`
if [ $PYTHONVERSION -lt "3" ]; then
echo "Requires at least Python 3.3"
exit 1
fi
export PYTHONPATH=$DIR
$PYBIN -B $DIR "$@"
